/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColdStartRouteImport } from './routes/cold-start'
import { Route as HealthRouteImport } from './routes/health'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as SimilarRouteImport } from './routes/similar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColdStartRoute = ColdStartRouteImport.update({
  id: '/cold-start',
  path: '/cold-start',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const SimilarRoute = SimilarRouteImport.update({
  id: '/similar',
  path: '/similar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cold-start': typeof ColdStartRoute
  '/health': typeof HealthRoute
  '/recommendations': typeof RecommendationsRoute
  '/similar': typeof SimilarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cold-start': typeof ColdStartRoute
  '/health': typeof HealthRoute
  '/recommendations': typeof RecommendationsRoute
  '/similar': typeof SimilarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cold-start': typeof ColdStartRoute
  '/health': typeof HealthRoute
  '/recommendations': typeof RecommendationsRoute
  '/similar': typeof SimilarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cold-start' | '/health' | '/recommendations' | '/similar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cold-start' | '/health' | '/recommendations' | '/similar'
  id:
    | '__root__'
    | '/'
    | '/cold-start'
    | '/health'
    | '/recommendations'
    | '/similar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColdStartRoute: typeof ColdStartRoute
  HealthRoute: typeof HealthRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SimilarRoute: typeof SimilarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cold-start': {
      id: '/cold-start'
      path: '/cold-start'
      fullPath: '/cold-start'
      preLoaderRoute: typeof ColdStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/similar': {
      id: '/similar'
      path: '/similar'
      fullPath: '/similar'
      preLoaderRoute: typeof SimilarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColdStartRoute: ColdStartRoute,
  HealthRoute: HealthRoute,
  RecommendationsRoute: RecommendationsRoute,
  SimilarRoute: SimilarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
